import type { PatternPreset } from '../patternTypes';

export const referencePresets: PatternPreset[] = [
  {
    id: 'ref-deep-blue-universe-01',
    modeId: 'ref-deep-blue-universe',
    label: 'Deep Blue Universe / 01',
    origin: 'reference',
    seed: 12017,
    color: {
      mainColor: 'blue',
      scheme: 'sameFamilyBlack',
      palette: {
        primary: [0.005, 0.026, 0.18],
        secondary: [0.025, 0.18, 0.66],
        accent: [0.26, 0.58, 1.0],
      },
    },
    move: { intensity: 'calm', program: 'directionalFlow', flowAngle: 0.12, speed: 0.68 },
    composition: { mode: 'full', seed: 12017 },
    fireflies: { enabled: true, density: 0.62, brightness: 0.86, twinkleSpeed: 0.78 },
    material: { membrane: 0.55, vein: 0.46, brightness: 0.88, contrast: 1.34 },
    domain: { scale: 1.16, stretch: 0.42, swirl: 0.42, flowAngle: 0.12 },
    effects: { glow: 0.82, specular: 0.25, grain: 0.06, scanline: 0.06 },
    blackHoleStyle: {
      coreScale: 0.88,
      gravityStrength: 1.05,
      gravityFalloff: 5.5,
      swirlStrength: 0.75,
      photonRingStrength: 0.68,
      photonRingWarp: 0.85,
      photonOrbitSpeed: 1.0,
      photonAngularFreq: 8.0,
      rimGlow: 0.66,
      rimColorBias: [0.5, 0.72, 1.0],
    },
    autoWeight: 1,
    tags: ['reference', 'universe', 'blue'],
  },
  {
    id: 'ref-pale-mineral-01',
    modeId: 'ref-pale-mineral',
    label: 'Pale Mineral / 01',
    origin: 'reference',
    seed: 21003,
    color: {
      mainColor: 'white',
      scheme: 'contrast',
      palette: {
        primary: [0.98, 0.94, 0.84],
        secondary: [0.66, 0.38, 0.22],
        accent: [0.14, 0.54, 0.56],
      },
    },
    move: { intensity: 'calm', program: 'stillBreath', flowAngle: -0.08, speed: 0.85 },
    composition: { mode: 'full', seed: 21003 },
    fireflies: { enabled: true, density: 0.18, brightness: 0.52, twinkleSpeed: 0.72 },
    material: { membrane: 0.58, vein: 0.32, brightness: 0.98, contrast: 1.04 },
    domain: { scale: 1.0, stretch: 0.08, swirl: 0.24, flowAngle: -0.08 },
    effects: { glow: 0.34, specular: 0.42, grain: 0.04, scanline: 0.02 },
    blackHoleStyle: {
      coreScale: 0.86,
      gravityStrength: 0.78,
      gravityFalloff: 6.8,
      swirlStrength: 0.45,
      photonRingStrength: 0.5,
      photonRingWarp: 0.58,
      photonOrbitSpeed: 0.75,
      photonAngularFreq: 7.0,
      rimGlow: 0.58,
      rimColorBias: [0.96, 0.58, 0.32],
    },
    autoWeight: 0.9,
    tags: ['reference', 'mineral', 'pale'],
  },
  {
    id: 'ref-magenta-green-cell-01',
    modeId: 'ref-magenta-green-cell',
    label: 'Magenta Green Cell / 01',
    origin: 'reference',
    seed: 30491,
    color: {
      mainColor: 'green',
      scheme: 'contrast',
      palette: {
        primary: [0.02, 0.12, 0.09],
        secondary: [0.02, 0.82, 0.58],
        accent: [0.76, 0.12, 0.84],
      },
    },
    move: { intensity: 'active', program: 'cellularPulse', flowAngle: 0.18, speed: 1.05 },
    fireflies: { enabled: true, density: 0.92, brightness: 1, twinkleSpeed: 1.1 },
    material: { membrane: 0.9, vein: 0.78, brightness: 1.08, contrast: 1.36 },
    domain: { scale: 1.12, stretch: 0.16, swirl: 0.88, flowAngle: 0.18 },
    effects: { glow: 0.92, specular: 0.7, grain: 0.1, scanline: 0.04 },
    blackHoleStyle: {
      coreScale: 0.86,
      gravityStrength: 1.05,
      gravityFalloff: 5.8,
      swirlStrength: 1.0,
      photonRingStrength: 0.64,
      photonRingWarp: 1.08,
      photonOrbitSpeed: 1.0,
      photonAngularFreq: 8.5,
      rimGlow: 0.68,
      rimColorBias: [0.38, 0.86, 0.72],
    },
    autoWeight: 0.85,
    tags: ['reference', 'cellular', 'magenta'],
  },
  {
    id: 'ref-blue-purple-vein-01',
    modeId: 'ref-blue-purple-vein',
    label: 'Blue Purple Vein / 01',
    origin: 'reference',
    seed: 40777,
    color: {
      mainColor: 'purple',
      scheme: 'accentColor',
      palette: {
        primary: [0.07, 0.24, 0.96],
        secondary: [0.56, 0.16, 0.9],
        accent: [1.0, 0.28, 0.52],
      },
    },
    move: { intensity: 'normal', program: 'directionalFlow', flowAngle: 0.5, speed: 1 },
    fireflies: { enabled: true, density: 0.8, brightness: 1, twinkleSpeed: 1 },
    material: { membrane: 0.52, vein: 0.72, brightness: 1.02, contrast: 1.22 },
    domain: { scale: 1.16, stretch: 0.5, swirl: 0.38, flowAngle: 0.5 },
    effects: { glow: 0.86, specular: 0.45, grain: 0.06, scanline: 0.12 },
    blackHoleStyle: {
      coreScale: 0.88,
      gravityStrength: 0.9,
      gravityFalloff: 5.8,
      swirlStrength: 0.6,
      photonRingStrength: 0.95,
      photonRingWarp: 0.8,
      photonOrbitSpeed: 0.95,
      photonAngularFreq: 8.5,
      rimGlow: 0.9,
      rimColorBias: [0.72, 0.82, 1.0],
    },
    autoWeight: 0.8,
    tags: ['reference', 'vein', 'blue-purple'],
  },
];
